<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Russell Industries Corp. - <?php echo $pageTitle;?></title>
<style type="text/css">
<!--
@import url("../css/screen.css");
@import url("../css/forms.css");
-->
</style>

</head>
<body>

<?php include_once ($_SERVER['DOCUMENT_ROOT'].'/inc/analytics.inc');?>  

<h1>Russell Industries Corp.</h1>

<?php include_once ($_SERVER['DOCUMENT_ROOT'].'/inc/nav.inc');?>  

